version: 2.1

environment: &environment
  LOG_LEVEL: WARN
  TEST_PORT: 3000
  TEST_HOST: http://localhost:3000
  TEST_REPORTS: /tmp/test-reports

jobs:
  functional_tests:
    working_directory: ~/repos/html-pipeline-task_list

    docker:
      - image: cimg/ruby:2.6.7-browsers
        environment:
          <<: *environment

    steps:
      - checkout

      - run:
          name: install bundler
          command: gem install bundler:2.2.17

      - run:
          name: check dependencies
          command: |
            bundle -v
            bundle exec ruby -v

      - restore_cache:
          keys:
            - html-pipeline-task_list-cache-v2-{{ checksum "html-pipeline-task_list.gemspec" }}
            - html-pipeline-task_list-cache-v2-

      - run:
          name: install gems
          command: bundle install

      - run:
          name: install packages
          command: npm install

      - save_cache:
          key: html-pipeline-task_list-cache-v2-{{ checksum "html-pipeline-task_list.gemspec" }}
          paths:
            - vendor
            - node_modules

      - run:
          name: run ruby unit tests
          command: bundle exec rake test

      - run:
          name: run javascript unit tests
          command: npm test

      - store_test_results:
          path: /tmp/test-results

  publish_to_rubygems:
    working_directory: ~/repos/html-pipeline-task_list

    docker:
      - image: circleci/ruby:2.6.8-buster-node
        environment:
          <<: *environment

    steps:
      - checkout

      - run:
          name: setup rubygems
          command: |
            mkdir ~/.gem
            echo -e "---\r\n:rubygems_api_key: $RUBYGEMS_API_KEY" > ~/.gem/credentials
            chmod 0600 ~/.gem/credentials

      - run:
          name: publish to Rubygems
          command: |
            gem build html-pipeline-task_list.gemspec
            gem push "html-pipeline-task_list-$(git describe --abbrev=0 --tags | cut -c 2-).gem"

workflows:
  version: 2
  build_and_test:
    jobs:
      - functional_tests
      - publish_to_rubygems:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
